export const siteLaunchDate = '2026-09-04T00:00:00+08:00';

export const languages = [
  { code: 'zh', label: '中' },
  { code: 'ja', label: '日' },
  { code: 'en', label: 'EN' },
  { code: 'ru', label: 'RU' },
];

export const socials = [
  { label: 'Email', href: 'mailto:1370228191@qq.com', value: '1370228191@qq.com' },
  { label: 'Bilibili', href: 'https://space.bilibili.com/65369165?spm_id_from=333.1387.0.0', value: '我的 B 站首页' },
  { label: 'GitHub', href: 'https://github.com/HaoQI-HAQ/haoqi_solo_WebBlog', value: 'HaoQI-HAQ' },
  { label: 'X / Twitter', href: '#social-pending', value: '待补充' },
  { label: 'Instagram', href: '#social-pending', value: '待补充' },
];

export const copy = {
  zh: {
    nav: ['首页', '游戏作品', '摄影', '音乐CD', '联系'],
    heroKicker: '游戏策划 · 视觉设计 · AI 编曲',
    heroTitle: '把玩法、影像与声音做成可以进入的世界。',
    heroBody: '先按作品集档案馆的结构搭底：游戏作品、摄影系统、音乐分析与侧边栏播放器都先可运行，后续再逐步替换真实内容。',
    explore: '进入作品',
    aboutTitle: '一半在系统里，一半在感觉里。',
    aboutBody: '我是浩祈。这个站点会逐步记录游戏作品、音乐分析和摄影路线。当前保持静态前端，上传与后台管理等功能后续再接存储和后端。',
    workTitle: '游戏作品',
    musicTitle: '个人音乐分析',
    photoTitle: '摄影作品',
    photoIntro: '摄影系统先按城市标签、年份归档、每组帧数、详情页和灯箱组织；图片暂用现有素材占位。',
    mapTitle: '拍摄城市地图',
    mapNote: '地图已并入摄影页面。当前是抽象占位图，后续可替换为中国 GeoJSON / SVG，并把每个城市关联到摄影相册。',
    uploadTitle: '上传图片入口',
    uploadBody: '当前是前端占位：真正上线的上传需要登录、对象存储和后端校验。这里先保留界面位置。',
    contactTitle: '联系与社交',
    runtime: '网站运行时间',
    days: '天',
    nowPlaying: '侧边栏播放器',
    noAudio: '音频文件待添加',
    download: '下载 / 跳转',
    allCities: '全部城市',
    allYears: '全部年份',
    frames: '帧',
    viewSet: '查看详情',
    openLightbox: '打开灯箱',
    close: '关闭',
    previous: '上一张',
    next: '下一张',
    camera: '器材',
    date: '日期',
  },
  ja: {
    nav: ['ホーム', 'ゲーム作品', '写真', '音楽CD', '連絡'],
    heroKicker: 'ゲームデザイン · ビジュアル · AI 作曲',
    heroTitle: '遊び、映像、音を、入れる世界にする。',
    heroBody: 'まずは作品アーカイブ、写真システム、音楽分析、サイドプレイヤーが動く土台を用意しました。',
    explore: '作品を見る',
    aboutTitle: '半分はシステム、半分は感覚。',
    aboutBody: '私は HAOQI。このサイトはゲーム、音楽分析、写真の旅を少しずつ記録します。',
    workTitle: 'ゲーム作品',
    musicTitle: '音楽分析',
    photoTitle: '写真作品',
    photoIntro: '都市タグ、年別アーカイブ、フレーム数、詳細、ライトボックスで整理します。',
    mapTitle: '撮影都市マップ',
    mapNote: '地図は写真ページに統合しました。後で中国 GeoJSON / SVG に差し替えます。',
    uploadTitle: '画像アップロード',
    uploadBody: '現在は UI の入口のみです。本番アップロードには認証、ストレージ、サーバー側検証が必要です。',
    contactTitle: '連絡とSNS',
    runtime: 'サイト稼働時間',
    days: '日',
    nowPlaying: 'サイドプレイヤー',
    noAudio: '音源は未追加',
    download: 'ダウンロード / 移動',
    allCities: '全都市',
    allYears: '全年',
    frames: '枚',
    viewSet: '詳細を見る',
    openLightbox: 'ライトボックス',
    close: '閉じる',
    previous: '前へ',
    next: '次へ',
    camera: '機材',
    date: '日付',
  },
  en: {
    nav: ['Home', 'Game Works', 'Photography', 'Music CD', 'Contact'],
    heroKicker: 'Game design · Visual direction · AI composition',
    heroTitle: 'I shape play, image and sound into worlds you can enter.',
    heroBody: 'The working base now follows an archive structure: games, photography, music notes and a persistent side player.',
    explore: 'Explore work',
    aboutTitle: 'Half system, half feeling.',
    aboutBody: 'I am Haoqi. This site will grow into an archive for games, music notes and photographic routes. Uploads and admin editing can come later.',
    workTitle: 'Game Works',
    musicTitle: 'Music Notes',
    photoTitle: 'Photography',
    photoIntro: 'The photography system starts with city tags, year archives, frame counts, detail views and a lightbox.',
    mapTitle: 'Shooting Map',
    mapNote: 'The map is integrated into the photography page and can later be replaced with China GeoJSON / SVG data.',
    uploadTitle: 'Image Upload Entry',
    uploadBody: 'This is a front-end placeholder. Real production uploads need auth, object storage and server-side validation.',
    contactTitle: 'Contact & Social',
    runtime: 'Site runtime',
    days: 'days',
    nowPlaying: 'Side Player',
    noAudio: 'Audio pending',
    download: 'Download / Open',
    allCities: 'All cities',
    allYears: 'All years',
    frames: 'frames',
    viewSet: 'View details',
    openLightbox: 'Open lightbox',
    close: 'Close',
    previous: 'Previous',
    next: 'Next',
    camera: 'Camera',
    date: 'Date',
  },
  ru: {
    nav: ['Главная', 'Игры', 'Фото', 'Музыка CD', 'Контакты'],
    heroKicker: 'Игровой дизайн · Визуал · AI музыка',
    heroTitle: 'Я собираю игру, образ и звук в миры, куда можно войти.',
    heroBody: 'Основа готова: игры, фотоархив, музыкальные заметки и боковой плеер.',
    explore: 'Смотреть работы',
    aboutTitle: 'Половина система, половина чувство.',
    aboutBody: 'Я Haoqi. Этот сайт постепенно станет архивом игр, музыкальных заметок и фотографических маршрутов.',
    workTitle: 'Игровые работы',
    musicTitle: 'Музыкальный анализ',
    photoTitle: 'Фотография',
    photoIntro: 'Фотоархив начинается с городских тегов, годов, числа кадров, деталей и лайтбокса.',
    mapTitle: 'Карта съёмок',
    mapNote: 'Карта встроена в страницу фотографии. Позже можно заменить её China GeoJSON / SVG.',
    uploadTitle: 'Загрузка изображений',
    uploadBody: 'Сейчас это только интерфейс. Для настоящей загрузки нужны вход, объектное хранилище и серверная проверка.',
    contactTitle: 'Контакты и соцсети',
    runtime: 'Сайт работает',
    days: 'дней',
    nowPlaying: 'Боковой плеер',
    noAudio: 'Аудио позже',
    download: 'Скачать / открыть',
    allCities: 'Все города',
    allYears: 'Все годы',
    frames: 'кадров',
    viewSet: 'Подробнее',
    openLightbox: 'Открыть',
    close: 'Закрыть',
    previous: 'Назад',
    next: 'Далее',
    camera: 'Камера',
    date: 'Дата',
  },
};

export const gameWorks = [
  {
    id: 'worlds-in-motion',
    number: '01',
    title: 'Worlds in motion',
    type: 'Game direction / narrative systems',
    summary: '玩法、叙事与节奏组织成可进入的世界。视频与下载链接预留。',
    image: '/assets/desktop-a-contact.jpg',
    videoUrl: 'https://videos.pexels.com/video-files/3129977/3129977-hd_1920_1080_25fps.mp4',
    downloadUrl: '#download-pending',
    status: 'Video demo',
  },
  {
    id: 'visual-language',
    number: '02',
    title: 'A visual language',
    type: 'Visual identity / art direction',
    summary: '从一张海报到一套可以持续生长的视觉系统。',
    image: '/assets/desktop-b-contact.jpg',
    videoUrl: '#video-pending',
    downloadUrl: '#download-pending',
    status: 'Asset pending',
  },
  {
    id: 'sound-material',
    number: '03',
    title: 'Sound as material',
    type: 'AI composition / sound studies',
    summary: '用算法和直觉寻找画面之外的情绪线索。',
    image: '/assets/tool-contact.jpg',
    videoUrl: '#video-pending',
    downloadUrl: '#download-pending',
    status: 'Music linked',
  },
];

export const musicTracks = [
  {
    id: 'rain-loop',
    title: 'Rain Loop Study',
    mood: 'Ambient / Soft system',
    analysis: '先放置曲目结构、情绪、BPM 和灵感来源；音频文件后续放入 public/audio 或 CDN。',
    src: '',
  },
  {
    id: 'city-night',
    title: 'City Night Sketch',
    mood: 'Night walk / Synthetic texture',
    analysis: '适合用作博客侧边栏播放器的低干扰背景音乐。',
    src: '',
  },
  {
    id: 'menu-pulse',
    title: 'Menu Pulse',
    mood: 'Game UI / Loop',
    analysis: '可用于游戏作品页的菜单循环音乐。',
    src: '',
  },
];

export const photoAlbums = [
  {
    id: 'guangzhou-night-walk',
    number: '01',
    title: 'Guangzhou Night Texture',
    city: '广州',
    year: '2026',
    date: '2026.09',
    frameCount: 36,
    camera: 'Camera / Pending',
    cover: '/assets/desktop-b-contact.jpg',
    summary: '夜色、街灯和潮湿玻璃的城市练习；当前作为摄影系统占位相册。',
    coordinates: { x: 57, y: 73 },
    tags: ['Street', 'Night', 'Archive placeholder'],
    images: [
      { src: '/assets/desktop-b-contact.jpg', caption: 'Night texture / placeholder 01' },
      { src: '/assets/tool-contact.jpg', caption: 'Neon reflection / placeholder 02' },
      { src: '/assets/desktop-a-contact.jpg', caption: 'Street frame / placeholder 03' },
    ],
  },
  {
    id: 'shenzhen-glass-weather',
    number: '02',
    title: 'Shenzhen Glass Weather',
    city: '深圳',
    year: '2026',
    date: '2026.08',
    frameCount: 28,
    camera: 'Camera / Pending',
    cover: '/assets/desktop-a-contact.jpg',
    summary: '高楼、玻璃和流动天气的空间练习；后续替换为真实摄影组。',
    coordinates: { x: 61, y: 78 },
    tags: ['Architecture', 'Weather', 'Archive placeholder'],
    images: [
      { src: '/assets/desktop-a-contact.jpg', caption: 'Glass weather / placeholder 01' },
      { src: '/assets/desktop-b-contact.jpg', caption: 'Urban surface / placeholder 02' },
      { src: '/assets/tool-contact.jpg', caption: 'Soft grid / placeholder 03' },
    ],
  },
  {
    id: 'shanghai-soft-grid',
    number: '03',
    title: 'Shanghai Soft Grid',
    city: '上海',
    year: '2025',
    date: '2025.12',
    frameCount: 42,
    camera: 'Camera / Pending',
    cover: '/assets/tool-contact.jpg',
    summary: '把建筑网格、雾气和人群节奏组织成一组安静的城市注脚。',
    coordinates: { x: 75, y: 55 },
    tags: ['Urban Study', 'Fog', 'Archive placeholder'],
    images: [
      { src: '/assets/tool-contact.jpg', caption: 'Soft grid / placeholder 01' },
      { src: '/assets/desktop-a-contact.jpg', caption: 'Crossing / placeholder 02' },
      { src: '/assets/desktop-b-contact.jpg', caption: 'Evening line / placeholder 03' },
    ],
  },
];

export const mapCities = [
  { city: '广州', x: 57, y: 73, count: 1 },
  { city: '深圳', x: 61, y: 78, count: 1 },
  { city: '上海', x: 75, y: 55, count: 1 },
  { city: '北京', x: 62, y: 32, count: 0 },
];
