export const siteLaunchDate = '2026-09-04T00:00:00+08:00';

export const languages = [
  { code: 'zh', label: '中' },
  { code: 'ja', label: '日' },
  { code: 'en', label: 'EN' },
  { code: 'ru', label: 'RU' },
];

export const socials = [
  { label: 'Email', href: 'mailto:1370228191@qq.com', value: '1370228191@qq.com' },
  { label: 'Bilibili', href: 'https://space.bilibili.com/65369165?spm_id_from=333.1387.0.0', value: '我的 B 站首页' },
  { label: 'GitHub', href: 'https://github.com/HaoQI-HAQ/haoqi_solo_WebBlog', value: 'HaoQI-HAQ' },
  { label: 'X / Twitter', href: '#social-pending', value: '待补充' },
  { label: 'Instagram', href: '#social-pending', value: '待补充' },
];

export const copy = {
  zh: {
    nav: ['关于', '游戏', '音乐', '摄影', '地图', '联系'],
    heroKicker: '游戏策划 · 视觉设计 · AI 编曲',
    heroTitle: '把玩法、影像与声音做成可以进入的世界。',
    heroBody: '这里先搭好个人博客的基础框架：作品展示、音乐播放器、摄影地图、上传入口、四语切换与日夜模式都已预留。',
    explore: '进入作品',
    aboutTitle: '一半在系统里，一半在感觉里。',
    aboutBody: '我是浩祈。这个站点会逐步记录游戏作品、视觉实验、音乐分析与摄影路线。当前先保持静态前端，等上传和后台管理成为刚需时再接后端与数据库。',
    workTitle: '游戏作品',
    musicTitle: '个人音乐分析',
    photoTitle: '摄影作品',
    mapTitle: '去过的城市',
    uploadTitle: '上传图片入口',
    uploadBody: '当前是前端占位：真正上线的上传需要登录、对象存储和后端校验。这里先保留界面位置，下一步再接 Supabase 或其他存储。',
    contactTitle: '联系与社交',
    runtime: '网站运行时间',
    days: '天',
    nowPlaying: '侧边栏播放器',
    noAudio: '音频文件待添加',
    download: '下载 / 跳转',
  },
  ja: {
    nav: ['紹介', 'ゲーム', '音楽', '写真', '地図', '連絡'],
    heroKicker: 'ゲームデザイン · ビジュアル · AI 作曲',
    heroTitle: '遊び、映像、音を、入れる世界にする。',
    heroBody: '作品、音楽プレイヤー、写真マップ、アップロード導線、多言語とテーマ切替の土台を先に用意しました。',
    explore: '作品を見る',
    aboutTitle: '半分はシステム、半分は感覚。',
    aboutBody: '私は HAOQI。このサイトはゲーム、視覚実験、音楽分析、写真の旅を少しずつ記録します。まずは静的フロントエンドで進めます。',
    workTitle: 'ゲーム作品',
    musicTitle: '音楽分析',
    photoTitle: '写真作品',
    mapTitle: '訪れた都市',
    uploadTitle: '画像アップロード',
    uploadBody: '現在は UI の入口のみです。本番アップロードには認証、ストレージ、サーバー側検証が必要です。',
    contactTitle: '連絡とSNS',
    runtime: 'サイト稼働時間',
    days: '日',
    nowPlaying: 'サイドプレイヤー',
    noAudio: '音源は未追加',
    download: 'ダウンロード / 移動',
  },
  en: {
    nav: ['About', 'Games', 'Music', 'Photo', 'Map', 'Contact'],
    heroKicker: 'Game design · Visual direction · AI composition',
    heroTitle: 'I shape play, image and sound into worlds you can enter.',
    heroBody: 'The base framework is ready: work archive, music player, photography map, upload entry, four languages and day/night mode.',
    explore: 'Explore work',
    aboutTitle: 'Half system, half feeling.',
    aboutBody: 'I am Haoqi. This site will grow into an archive for games, visual experiments, music notes and photographic routes. It stays static first, then gains backend and database only when uploads and admin editing need them.',
    workTitle: 'Game Works',
    musicTitle: 'Music Notes',
    photoTitle: 'Photography',
    mapTitle: 'Cities Visited',
    uploadTitle: 'Image Upload Entry',
    uploadBody: 'This is a front-end placeholder. Real production uploads need auth, object storage and server-side validation.',
    contactTitle: 'Contact & Social',
    runtime: 'Site runtime',
    days: 'days',
    nowPlaying: 'Side Player',
    noAudio: 'Audio pending',
    download: 'Download / Open',
  },
  ru: {
    nav: ['Обо мне', 'Игры', 'Музыка', 'Фото', 'Карта', 'Контакты'],
    heroKicker: 'Игровой дизайн · Визуал · AI музыка',
    heroTitle: 'Я собираю игру, образ и звук в миры, куда можно войти.',
    heroBody: 'Базовый каркас готов: архив работ, плеер, фотокарта, вход загрузки, четыре языка и дневная/ночная тема.',
    explore: 'Смотреть работы',
    aboutTitle: 'Половина система, половина чувство.',
    aboutBody: 'Я Haoqi. Этот сайт постепенно станет архивом игр, визуальных экспериментов, музыкальных заметок и фотографических маршрутов.',
    workTitle: 'Игровые работы',
    musicTitle: 'Музыкальный анализ',
    photoTitle: 'Фотография',
    mapTitle: 'Города',
    uploadTitle: 'Загрузка изображений',
    uploadBody: 'Сейчас это только интерфейс. Для настоящей загрузки нужны вход, объектное хранилище и серверная проверка.',
    contactTitle: 'Контакты и соцсети',
    runtime: 'Сайт работает',
    days: 'дней',
    nowPlaying: 'Боковой плеер',
    noAudio: 'Аудио позже',
    download: 'Скачать / открыть',
  },
};

export const gameWorks = [
  {
    id: 'worlds-in-motion',
    number: '01',
    title: 'Worlds in motion',
    type: 'Game direction / narrative systems',
    summary: '玩法、叙事与节奏组织成可进入的世界。视频与下载链接预留。',
    image: '/assets/desktop-a-contact.jpg',
    videoUrl: 'https://videos.pexels.com/video-files/3129977/3129977-hd_1920_1080_25fps.mp4',
    downloadUrl: '#download-pending',
    status: 'Video demo',
  },
  {
    id: 'visual-language',
    number: '02',
    title: 'A visual language',
    type: 'Visual identity / art direction',
    summary: '从一张海报到一套可以持续生长的视觉系统。',
    image: '/assets/desktop-b-contact.jpg',
    videoUrl: '#video-pending',
    downloadUrl: '#download-pending',
    status: 'Asset pending',
  },
  {
    id: 'sound-material',
    number: '03',
    title: 'Sound as material',
    type: 'AI composition / sound studies',
    summary: '用算法和直觉寻找画面之外的情绪线索。',
    image: '/assets/tool-contact.jpg',
    videoUrl: '#video-pending',
    downloadUrl: '#download-pending',
    status: 'Music linked',
  },
];

export const musicTracks = [
  {
    id: 'rain-loop',
    title: 'Rain Loop Study',
    mood: 'Ambient / Soft system',
    analysis: '先放置曲目结构、情绪、BPM 和灵感来源；音频文件后续放入 public/audio 或 CDN。',
    src: '',
  },
  {
    id: 'city-night',
    title: 'City Night Sketch',
    mood: 'Night walk / Synthetic texture',
    analysis: '适合用作博客侧边栏播放器的低干扰背景音乐。',
    src: '',
  },
  {
    id: 'menu-pulse',
    title: 'Menu Pulse',
    mood: 'Game UI / Loop',
    analysis: '可用于游戏作品页的菜单循环音乐。',
    src: '',
  },
];

export const photos = [
  { id: 'guangzhou-night', title: 'Guangzhou Night Texture', city: '广州', image: '/assets/desktop-b-contact.jpg', year: '2026', tag: 'Street / Night' },
  { id: 'shenzhen-glass', title: 'Shenzhen Glass Weather', city: '深圳', image: '/assets/desktop-a-contact.jpg', year: '2026', tag: 'Architecture' },
  { id: 'shanghai-fog', title: 'Shanghai Soft Grid', city: '上海', image: '/assets/tool-contact.jpg', year: '2026', tag: 'Urban Study' },
];

export const mapCities = [
  { city: '广州', x: 57, y: 73, count: 1 },
  { city: '深圳', x: 61, y: 78, count: 1 },
  { city: '上海', x: 75, y: 55, count: 1 },
  { city: '北京', x: 62, y: 32, count: 0 },
];
